fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-ast   # checks Python syntax
    - id: check-json  # checks JSON syntax
    - id: check-yaml  # checks YAML syntax
    - id: check-toml  # checks TOML syntax
    - id: end-of-file-fixer  # checks there is a newline at the end of the file
    - id: trailing-whitespace  # trims trailing whitespace
    - id: check-merge-conflict  # checks for no merge conflict strings
    - id: check-shebang-scripts-are-executable  # checks all shell scripts have executable permissions
    - id: mixed-line-ending  # normalizes line endings
    - id: no-commit-to-branch  # prevents committing to main
    #- id: pretty-format-json  # indents and sorts JSON files    # FIXME: JSON schema generator conflicts with this