name: Test / instructor-embedders

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'components/instructor-embedders/**'
      - '.github/workflows/components_instructor_embedders.yml'

defaults:
  run:
    working-directory: components/instructor-embedders

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Install instructor-embedders
      run: |
        pip install -e .[dev]

    - name: Lint
      run: hatch run lint:all

    - name: Run tests and track code coverage
      run: hatch run cov