# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0
name: Test / text2speech

on:
  push:
    paths:
      - 'nodes/text2speech/**'
      - '.github/workflows/nodes__text2speech.yml'

env:
  PACKAGE: nodes/text2speech/
  MODULE: text2speech
  PYTEST_PARAMS: --maxfail=5 --durations=10

jobs:

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      with:
        package: ${{ env.PACKAGE }}

    - name: Install audio libraries
      if: matrix.os == "ubuntu-latest"
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 ffmpeg

    - name: Install dependencies
      run: pip install ${{ env.PACKAGE }}[dev]

    - name: Mypy
      run: |
        mkdir .mypy_cache/
        mypy --install-types --non-interactive .


  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      with:
        package: ${{ env.PACKAGE }}

    - name: Install audio libraries
      if: matrix.os == "ubuntu-latest"
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 ffmpeg

    - name: Install dependencies
      run: pip install ${{ env.PACKAGE }}[dev]

    - name: Pylint
      run: |
        cd ${{ env.PACKAGE }}
        pylint -ry -j 0 ${{ env.MODULE }}/

  unit-tests:
    name: Unit / ${{ matrix.os }}
    needs:
      - mypy
      - pylint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # windows-latest --> No audio deps available for Windows.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/
        with:
          package: ${{ env.PACKAGE }}

      - name: Install audio libraries
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg

      - name: Install deps
        run: pip install ${{ env.PACKAGE }}[dev]

      - name: Run
        run: pytest ${{ env.PYTEST_PARAMS }} -m "unit" ${{ env.PACKAGE }}


  integration-tests:
    name: Integration / ${{ matrix.os }}
    needs:
      - unit-tests
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # windows-latest --> No audio deps available for Windows.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      with:
        package: ${{ env.PACKAGE }}

    - name: Install audio libraries
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 ffmpeg

    - name: Install deps
      run: pip install ${{ env.PACKAGE }}[dev]

    - name: Run tests
      env:
        TOKENIZERS_PARALLELISM: 'false'  # Avoid logspam by tokenizers
      run: |
        pytest ${{ env.PYTEST_PARAMS }} -m "integration" ${{ env.PACKAGE }}
