# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0
name: Test speech2text

on:
  workflow_dispatch:
  push:
    paths:
      - 'nodes/speech2text/**'
      - '.github/workflows/test__speech2text.yml'

env:
  PACKAGE: nodes/speech2text/
  PYTEST_PARAMS: --maxfail=5 --durations=10

jobs:

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      with:
        package: ${{ env.PACKAGE }}

    - name: Install dependencies
      run: pip install ${{ env.PACKAGE }}[dev]

    - name: Mypy
      # NOTE: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
      # FIXME --install-types does not work properly yet, see https://github.com/python/mypy/issues/10600
      # We should see if there's a better way than --ignore-missing-imports
      run: mypy ${{ env.PACKAGE }} --ignore-missing-imports

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      with:
        package: ${{ env.PACKAGE }}

    - name: Pylint
      run: |
        cd ${{ env.PACKAGE }}
        pylint -ry -j 0 speech2text/

  unit-tests:
    name: Unit / ${{ matrix.os }}
    needs:
      - mypy
      - pylint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows-latest --> No audio deps available for Windows.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/
        with:
          package: ${{ env.PACKAGE }}

      - name: Install audio libraries
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg
          wget https://raw.githubusercontent.com/readbeyond/aeneas/master/install_dependencies.sh
          bash install_dependencies.sh
          rm install_dependencies.sh

      - name: Install Haystack
        run: pip install ${{ env.PACKAGE }}[whisper,wav2vec,aeneas,dev]

      - name: Run
        run: pytest ${{ env.PYTEST_PARAMS }} -m "unit" ${{ env.PACKAGE }}

  integration-tests:
    name: Integration / ${{ matrix.os }}
    needs:
      - unit-tests
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows-latest --> No audio deps available for Windows.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      with:
        package: ${{ env.PACKAGE }}

    - name: Install audio libraries
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 ffmpeg
        wget https://raw.githubusercontent.com/readbeyond/aeneas/master/install_dependencies.sh
        bash install_dependencies.sh
        rm install_dependencies.sh

    - name: Install Haystack
      run: pip install ${{ env.PACKAGE }}[whisper,wav2vec,aeneas,dev]

    - name: Run tests
      env:
        TOKENIZERS_PARALLELISM: 'false'  # Avoid logspam by tokenizers
      run: |
        pytest ${{ env.PYTEST_PARAMS }} -m "integration" ${{ env.PACKAGE }}

  yaml-schema:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/
        with:
          package: ${{ env.PACKAGE }}

      - name: Install audio libraries
        run: |
          sudo apt-get update
          sudo apt-get install libsndfile1 ffmpeg
          wget https://raw.githubusercontent.com/readbeyond/aeneas/master/install_dependencies.sh
          bash install_dependencies.sh
          rm install_dependencies.sh

      - name: Install package
        run: pip install -U ${{ env.PACKAGE }}[whisper,wav2vec,aeneas,dev]

      - name: Update pipeline YAML schemas
        run: python .github/utils/generate_json_schema.py -f speech2text -m=speech2text.transcriber,speech2text.aligner

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo "##################################################################################################"
            git diff
            echo "##################################################################################################"
            echo "# "
            echo "# CHECK FAILED! The YAML schemas for this package were not updated."
            echo "# "
            echo "# Please generate the new schemas locally:"
            echo "# "
            echo "#     python .github/utils/generate_json_schema.py -o ${{ env.PACKAGE }}/json-schemas -v 0.0.1 -t "speech2text nodes schema" -d "schema for speech2text nodes" -p speech2text -m speech2text"
            echo "# "
            echo "# Or see https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md for help."
            echo "# "
            echo "# If you have further problems, please open an issue: https://github.com/deepset-ai/haystack-extras/issues"
            echo "# "
            echo "##################################################################################################"
            exit 1
          fi
