name: Test text2speech_nodes

on:
  workflow_dispatch:
  push:
    paths:
      - 'nodes/text2speech-nodes/**'
      - '.github/workflows/test--text2speech_nodes.yml'

env:
  PACKAGE: nodes/text2speech-nodes/
  PYTEST_PARAMS: --maxfail=5 --durations=10

jobs:

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      package: ${{ env.PACKAGE }}

    - name: Install dependencies
      run: pip install ${{ env.PACKAGE }}[dev]

    - name: Mypy
      # NOTE: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
      # FIXME --install-types does not work properly yet, see https://github.com/python/mypy/issues/10600
      # We should see if there's a better way than --ignore-missing-imports
      run: mypy ${{ env.PACKAGE }} --ignore-missing-imports

    # - uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     channel: '#haystack'
    #   if: failure() && github.repository_owner == 'deepset-ai' && github.ref == 'refs/heads/main'

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      package: ${{ env.PACKAGE }}

    - name: Pylint
      run: pylint -ry -j 0 ${{ env.PACKAGE }}

    # - uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     channel: '#haystack'
    #   if: failure() && github.repository_owner == 'deepset-ai' && github.ref == 'refs/heads/main'

  unit-tests:
    name: Unit / ${{ matrix.os }}
    needs:
      - mypy
      - pylint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows-latest --> No audio deps available for Windows.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/
        package: ${{ env.PACKAGE }}

      - name: Install Haystack
        run: pip install ${{ env.PACKAGE }}[dev]

      - name: Run
        run: pytest ${{ env.PYTEST_PARAMS }} -m "unit" ${{ env.PACKAGE }}

      # - uses: act10ns/slack@v1
      #   with:
      #     status: ${{ job.status }}
      #     channel: '#haystack'
      #   if: failure() && github.repository_owner == 'deepset-ai' && github.ref == 'refs/heads/main'

  integration-tests:
    name: Integration / ${{ matrix.os }}
    needs:
      - unit-tests
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # windows-latest --> No audio deps available for Windows.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/python_cache/
      package: ${{ env.PACKAGE }}

    - name: Install audio libraries
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1 ffmpeg

    - name: Install Haystack
      run: pip install ${{ env.PACKAGE }}[dev]

    - name: Run tests
      env:
        TOKENIZERS_PARALLELISM: 'false'  # Avoid logspam by tokenizers
      run: |
        pytest ${{ env.PYTEST_PARAMS }} -m "integration" ${{ env.PACKAGE }}

    # - uses: act10ns/slack@v1
    #   with:
    #     status: ${{ job.status }}
    #     channel: '#haystack'
    #   if: failure() && github.repository_owner == 'deepset-ai' && github.ref == 'refs/heads/main'


  yaml-schema:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/python_cache/
        package: ${{ env.PACKAGE }}

      - name: Install sndfile
        run: sudo apt update && sudo apt-get install libsndfile1 ffmpeg

      - name: Install package
        run: pip install -U ${{ env.PACKAGE }}[dev]

      - name: Update pipeline YAML schemas
        run: python .github/utils/generate_json_schema.py -o ${{ env.PACKAGE }}/json-schemas -v 0.0.1 -t "text2speech nodes schema" -d "schema for text2speech nodes" -p text2speech-nodes -m text2speech_nodes

      - name: Check status
        run: |
          if [[ `git status --porcelain` ]]; then
            git status
            echo "##################################################################################################"
            git diff
            echo "##################################################################################################"
            echo "# "
            echo "# CHECK FAILED! The YAML schemas for this package were not updated."
            echo "# "
            echo "# Please generate the new schemas locally:"
            echo "# "
            echo "#     python .github/utils/generate_json_schema.py -o ${{ env.PACKAGE }}/json-schemas -v 0.0.1 -t "text2speech nodes schema" -d "schema for text2speech nodes" -p text2speech-nodes -m text2speech_nodes"
            echo "# "
            echo "# Or see https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md for help."
            echo "# "
            echo "# If you have further problems, please open an issue: https://github.com/deepset-ai/haystack-extras/issues"
            echo "# "
            echo "##################################################################################################"
            exit 1
          fi
